// Canonical English quest data stays unchanged, including existing version-1 saves.
// Translate at the presentation boundary so old journals are localized too.
export const messages = {
  "BEN":"БЕН", "MO":"МО", "BARTENDER":"БАРМЕН", "GUARD":"ОХРАННИК", "TERMINAL":"ТЕРМИНАЛ",
  "Bike keys":"Ключи от байка", "Siphon hose":"Шланг", "Beef jerky":"Вяленое мясо", "Empty fuel can":"Пустая канистра", "Full fuel can":"Канистра с бензином", "Wrench":"Гаечный ключ", "Pickup magnet":"Магнит на тросе", "Front forks":"Передняя вилка", "Evidence photos":"Фотографии-улики", "Corley’s tape":"Кассета Корли", "Spare fuse":"Предохранитель",
  "My Corley keys. The only jewelry I need.":"Ключи от моего «Корли». Другие украшения мне ни к чему.",
  "A length of rubber hose. Smells like the last decade.":"Кусок резинового шланга. Пахнет прошлым десятилетием.",
  "Biker food. Or a peace offering to something with bigger teeth.":"Еда байкера. Или мирное подношение кому-то с зубами покрупнее.",
  "Empty. An accurate summary of my fuel situation.":"Пустая. Точное описание моих запасов бензина.",
  "A gallon of questionable gas. My bike is not a snob.":"Несколько литров сомнительного бензина. Мой байк не привередлив.",
  "Fits a front axle. Also most things that need persuading.":"Подходит для передней оси. И для многих других вещей, которые нужно уговорить.",
  "A strong magnet on a cable. For things my fingers cannot reach.":"Сильный магнит на тросе. Достанет то, до чего не дотянутся пальцы.",
  "Straight Corley forks. Better than the pretzels on my bike.":"Ровная вилка от «Корли». Лучше кренделя, который сейчас стоит на моём байке.",
  "Miranda’s contact prints. Ripburger, Corley, and a very clear motive.":"Снимки Миранды. Рипбургер, Корли и совершенно ясный мотив.",
  "Malcolm’s recorded will. He leaves the company to Maureen.":"Завещание Малкольма на кассете. Он оставляет компанию Морин.",
  "A 20-amp industrial fuse. Small part, big responsibility.":"Промышленный предохранитель на 20 ампер. Маленькая деталь, большая ответственность.",
  "The Kickstand":"Бар «Кикстэнд»", "THE KICKSTAND":"БАР «КИКСТЭНД»", "Mo’s Garage":"Гараж Мо", "MO’S GARAGE":"ГАРАЖ МО", "The Salvage Yard":"Свалка", "THE SALVAGE YARD":"СВАЛКА", "Corley Motors":"«Корли Моторс»", "CORLEY MOTORS":"«КОРЛИ МОТОРС»",
  "MELONWEED OUTSKIRTS · 19:42":"ОКРАИНА МЕЛОНВИДА · 19:42", "MELONWEED · 20:16":"МЕЛОНВИД · 20:16", "OLD ROUTE 9 · 20:38":"СТАРОЕ ШОССЕ № 9 · 20:38", "CORLEY INDUSTRIAL PARK · 23:07":"ЗАВОД КОРЛИ · 23:07",
  "A bar, a bad headache, and the start of trouble.":"Бар, головная боль и первые неприятности.",
  "Good tools. Better company. Your only way back.":"Хорошие инструменты. Ещё лучше — компания. Твой шанс вернуться на дорогу.",
  "Spare parts. Stale gas. Very sharp teeth.":"Запчасти. Старый бензин. Очень острые зубы.",
  "The shareholders are waiting. So is the truth.":"Акционеры ждут. Правда тоже.",
  "The Kickstand. Where the drinks are warm and the welcome is colder.":"«Кикстэнд». Напитки тёплые, приём холодный.",
  "Mo’s garage. Smells like gasoline and second chances.":"Гараж Мо. Пахнет бензином и вторым шансом.",
  "One man’s scrap heap is another man’s way out of town.":"Для кого-то это груда хлама. Для меня — билет из города.",
  "Ripburger has an audience. Time to give him something to talk about.":"Рипбургер собрал публику. Пора подкинуть ему тему для выступления.",
  "Woke up behind the Kickstand. The Polecats have disappeared with a man named Ripburger. First: find my keys.":"Очнулся за «Кикстэндом». «Хорьки» уехали с каким-то Рипбургером. Для начала надо найти ключи.",
  "This is not a compatible Dust & Deception save.":"Это сохранение не подходит для игры «Байк обреченный».",
  "The save contains invalid game data.":"В сохранении повреждены данные игры.",
  "The save contains an invalid inventory.":"В сохранении повреждён инвентарь.",
  "The save contains invalid journal data.":"В сохранении повреждён журнал.",
  "The save contains invalid speech history.":"В сохранении повреждена история прослушанных реплик.",
  "The save contains invalid quest flags.":"В сохранении повреждены данные заданий.",
  "The save contains invalid progress data.":"В сохранении повреждены данные прохождения.",
  "The save contains an invalid completion time.":"В сохранении некорректно указано время завершения.",
  "The save location does not match your progress.":"Локация в сохранении не соответствует этапу игры.",
  "The save location does not match your bike repairs.":"До этой локации нельзя добраться с текущим состоянием байка.",
  "Your saved game could not be read. A new ride is ready; the previous save is kept until you choose to replace it.":"Не удалось прочитать сохранение. Можно начать заново; прежний файл останется нетронутым, пока вы не решите его заменить.",
  "THE ROAD GOES ON":"ДОРОГА ПРОДОЛЖАЕТСЯ", "THE TRUTH HAS AN ENGINE":"У ПРАВДЫ ЕСТЬ МОТОР", "DUST & DECEPTION":"БАЙК ОБРЕЧЕННЫЙ", "A RUDE AWAKENING":"ГРУБОЕ ПРОБУЖДЕНИЕ",
  "The Polecats ride free. The road is yours.":"«Хорьки» снова свободны. Дорога твоя.",
  "Find your keys. Find your gang.":"Найди ключи. Найди свою банду.",
  "Get your motorcycle back on the road.":"Верни свой мотоцикл на дорогу.",
  "Repair the forks, fill the tank, tighten the axle.":"Замени вилку, залей бензин, затяни ось.",
  "Find the photographer’s evidence.":"Найди фотографии, которые докажут правду.",
  "Show Mo what really happened to her father.":"Покажи Мо, что случилось с её отцом.",
  "Restore power to Corley’s broadcast terminal.":"Восстанови питание терминала на заводе Корли.",
  "Find a way into the broadcast terminal.":"Получи доступ к терминалу трансляции.",
  "Load the photos and Corley’s last will.":"Загрузи фотографии и завещание Корли.",
  "Interrupt Ripburger’s speech. Let the truth ride.":"Прерви речь Рипбургера. Пусть все узнают правду.",
  "Journal updated":"Журнал обновлён",
  "Dumpster":"Мусорный контейнер", "Bar door":"Дверь бара", "Bartender":"Бармен", "Kickstand sign":"Вывеска бара", "Ben’s motorcycle":"Мотоцикл Бена", "Maureen":"Морин", "Tool bench":"Верстак", "Workshop radio":"Радиоприёмник", "Contented junkyard dog":"Сытый сторожевой пёс", "Junkyard dog":"Сторожевой пёс", "Chrome front forks":"Хромированная вилка", "Pump with siphon hose":"Колонка со шлангом", "Old fuel pump":"Старая бензоколонка", "Rusted car":"Ржавый автомобиль", "Watchman’s shack":"Будка сторожа", "Broadcast terminal":"Терминал трансляции", "Service terminal":"Служебный терминал", "Memorial plaque":"Памятная табличка", "Night guard":"Ночной охранник", "Open power cabinet":"Открытый электрощит", "Power cabinet":"Электрощит", "Shareholders’ meeting":"Собрание акционеров",
  "Corley’s is fifty miles away. I need a working motorcycle first.":"До завода Корли восемьдесят километров. Сначала нужен исправный мотоцикл.",
  "I need my keys before I go wandering off. They have to be around here.":"Прежде чем куда-то идти, надо найти ключи. Они должны быть где-то рядом.",
  "Already here. Still not getting paid by the hour.":"Я уже здесь. И мне всё ещё не платят за проведённое тут время.",
  "The Corley lives. But the radio says Malcolm Corley is dead and the Polecats are wanted. Ripburger set us up. Need evidence.":"«Корли» ожил. Но по радио говорят, что Малкольм Корли мёртв, а «Хорьков» объявили в розыск. Рипбургер нас подставил. Нужны доказательства.",
  "She’s running. But listen to that radio… Dad’s dead. They’re blaming your gang. Ripburger did this, Ben. Find something that proves it.":"Завелась. Но послушай радио… Папа мёртв. Винят твою банду. Это сделал Рипбургер, Бен. Найди доказательства.",
  "CHAPTER 02 · DUST & DECEPTION":"ГЛАВА 02 · БАЙК ОБРЕЧЕННЫЙ",
  "That is not here anymore.":"Этого здесь больше нет.", "One thing at a time.":"Всё по порядку.", "I don’t have that.":"У меня этого нет.",
  "He’s busy chewing. Best conversation I’ve had all day.":"Он занят едой. Лучший разговор за весь день.",
  "Nice dog. Nice, incredibly unreasonable dog.":"Хороший пёс. Хороший, совершенно несговорчивый пёс.",
  "Come on, girl. We’ve got miles left in us.":"Давай, подруга. Впереди ещё много километров.",
  "I asked for regular. It’s giving me the silent treatment.":"Я попросил обычного бензина. В ответ — молчание.",
  "I already spent enough time in there. We’re not getting closer.":"Я и так провёл там достаточно времени. Дружбы не получится.",
  "It isn’t much of a talker.":"Разговорчивостью не отличается.",
  "One solid kick. My keys fall out of a seam in the dumpster. Subtlety is overrated.":"Один хороший пинок — и ключи выпадают из щели контейнера. Деликатность переоценена.",
  "Something metal rattles behind the drain grate. My boot won’t fit. For once.":"За сливной решёткой что-то металлическое. Сапог туда не пролезет. Бывает же.",
  "Already made my point.":"Мою мысль уже поняли.",
  "I kick trouble. Not my motorcycle.":"Я пинаю неприятности. Свой байк — нет.",
  "I need allies. I’m not kicking this problem.":"Мне нужны союзники. Пинками их не завоюешь.",
  "Bolted steel. My boot loses that argument. A wrench might win.":"Сталь на болтах. Сапогу не справиться. Ключу — вполне.",
  "Kicking a gasoline pump. Even I have limits.":"Пнуть бензоколонку? Даже у меня есть пределы.",
  "My boot isn’t the right tool for this job.":"Сапог для этого не подходит.",
  "The lid is jammed. Something jingles when I shove it. This calls for the persuasive boot.":"Крышку заклинило. Толкаю — внутри звенит. Тут нужен убедительный пинок.",
  "A little metal photo tin is stuck behind the drain grate. Too deep to reach. A magnet on a cable would do it.":"За сливной решёткой застряла жестянка с фотографиями. Рукой не достать. Помог бы магнит на тросе.",
  "My least favorite hotel. Zero stars. No breakfast.":"Мой нелюбимый отель. Ноль звёзд. Завтрака нет.",
  "The bartender saw everything. He’s wearing the face of a man who wishes he hadn’t.":"Бармен всё видел. И очень хотел бы развидеть.",
  "The Kickstand. A place to park your bike and misplace your dignity.":"«Кикстэнд». Место, где паркуют байк и теряют достоинство.",
  "Maureen. Knows engines better than most people know their own names.":"Морин. Разбирается в моторах лучше, чем большинство людей — в собственной жизни.",
  "My Corley. Somebody’s messed with the front end. Select my keys from the inventory and use them here.":"Мой «Корли». Кто-то покопался в передней подвеске. Надо выбрать ключи в инвентаре и применить к байку.",
  "Straight forks. Tight axle. Fuel in the tank. That’s the sound of possibilities.":"Ровная вилка. Затянутая ось. Бензин в баке. Звучит как свобода.",
  "straight front forks":"ровная передняя вилка", "gasoline":"бензин", "the axle tightened with a wrench":"затяжка оси гаечным ключом", "the evidence photos":"фотографии-улики", "Corley’s recorded will":"запись завещания Корли",
  "Borrowed an empty fuel can. Now for the difficult half of that equation.":"Одолжил пустую канистру. Теперь осталось найти то, чем её наполнить.",
  "An empty gasoline can. Use it to pick it up.":"Пустая канистра. Действие «Действие» — и она моя.",
  "Mo’s workbench: a wrench, a pickup magnet, and a little box of spare fuses. Use the bench to take a tool.":"Верстак Мо: гаечный ключ, магнит на тросе и коробка предохранителей. Выбери действие «Действие» и нажми на верстак.",
  "“Corley Motors shareholders will hear from acting president Adrian Ripburger tonight.” Not if I can help it.":"«Сегодня перед акционерами выступит и. о. президента „Корли Моторс“ Эдриан Рипбургер». Только через мой труп.",
  "A weather report. Dry. Dusty. Continued chance of bad decisions.":"Прогноз погоды. Сухо. Пыльно. Вероятность плохих решений по-прежнему высокая.",
  "He’s found a higher calling: beef jerky.":"Он нашёл смысл жизни: вяленое мясо.",
  "A junkyard dog with a very personal attachment to those front forks. Maybe something edible would change his mind.":"Пёс очень привязан к этой вилке. Может, что-нибудь съедобное поможет ему пересмотреть ценности.",
  "Straight front forks, courtesy of a dog with a full mouth.":"Ровная вилка. Спасибо псу, которому сейчас не до меня.",
  "The dog snaps before I can reach the forks. Need to make a friend first.":"Пёс щёлкает зубами раньше, чем я дотягиваюсь до вилки. Сначала надо подружиться.",
  "A straight pair of Corley forks. Exactly what my front end is missing. Their owner appears to have teeth.":"Ровная вилка от «Корли». Именно то, что нужно. Похоже, у её владельца есть зубы.",
  "The hose is connected. Use an empty fuel can on the pump to siphon the gas.":"Шланг подсоединён. Примени пустую канистру к колонке, чтобы слить бензин.",
  "The pump has gas, but no working motor. Need a hose to siphon it, and a can to catch it.":"Бензин есть, насос не работает. Нужны шланг, чтобы слить, и канистра, чтобы собрать.",
  "The car lost an argument with a larger car. The forks beside it look fine, though.":"Машина проиграла спор машине покрупнее. А вилка рядом выглядит целой.",
  "Locked. The watchman’s gone. His dog is handling customer complaints.":"Заперто. Сторож ушёл. Жалобы посетителей принимает его пёс.",
  "A night guard. Tired eyes. A faded Polecats pin on his jacket.":"Ночной охранник. Усталые глаза. На куртке — выцветший значок «Хорьков».",
  "The plaque reads: “Malcolm Corley. First victory, race number 2040.” Someone scratched “SERVICE PIN = FIRST VICTORY” underneath.":"На табличке: «Малкольм Корли. Первая победа. Гоночный номер 2040». Ниже нацарапано: «КОД ТЕРМИНАЛА = ПЕРВАЯ ПОБЕДА».",
  "Corley’s first winning race number: 2040. That’s the service PIN.":"Номер Корли в первой победной гонке: 2040. Это и есть код терминала.",
  "The new fuse is holding. The broadcast terminal has power.":"Новый предохранитель держится. Терминал получает питание.",
  "The cabinet is open. The 20-amp fuse is blown. Mo keeps spares on her workbench.":"Щит открыт. Предохранитель на 20 ампер перегорел. У Мо на верстаке есть запасные.",
  "A power cabinet, bolted shut. The status lamp is dead. Those bolts look wrench-sized.":"Электрощит закрыт на болты. Лампочка не горит. Болты как раз под мой ключ.",
  "Upstairs, Ripburger is promising a brighter future. From here, it looks a lot like a minivan.":"Наверху Рипбургер обещает светлое будущее. Отсюда оно подозрительно похоже на минивэн.",
  "The broadcast terminal feeds the meeting upstairs. It has a photo scanner, a tape deck, and a big TRANSMIT button.":"Терминал подключён к экрану в зале. Есть сканер фотографий, кассетная дека и большая кнопка «ТРАНСЛЯЦИЯ».",
  "A service terminal, wired to the presentation upstairs. A keypad beside the door asks for a four-digit PIN.":"Терминал подключён к презентации наверху. Клавиатура у двери просит четырёхзначный код.",
  "No power. I need to get that cabinet working first.":"Нет питания. Сначала надо разобраться с электрощитом.",
  "Four digits between me and a very uncomfortable speech.":"Четыре цифры — и чья-то речь станет очень неловкой.",
  "The truth is already out. No encore needed.":"Правда уже прозвучала. На бис не требуется.",
  "Broadcast the photos and Malcolm’s will. Ripburger is exposed, Maureen inherits Corley Motors, and the Polecats are cleared. Time to ride.":"Показал фотографии и завещание Малкольма. Рипбургер разоблачён, компания переходит Морин, а с «Хорьков» сняты обвинения. Пора в путь.",
  "The photos fill the screen. Malcolm’s voice fills the room. Ripburger runs out of words. Outside, a dozen engines start. That’s my cue.":"На экране — фотографии. В зале — голос Малкольма. У Рипбургера кончились слова. Снаружи заводится дюжина моторов. Мне пора.",
  "THE POLECATS RIDE FREE":"«ХОРЬКИ» СНОВА СВОБОДНЫ", "Nothing else to do here.":"Больше здесь делать нечего.",
  "The bike was sabotaged. Maureen helped haul it to her garage. Need forks, fuel, and a tightened axle. The salvage yard is within walking distance.":"Байк вывели из строя. Морин помогла дотащить его до гаража. Нужны вилка, бензин и затяжка оси. До свалки можно дойти пешком.",
  "The engine coughs. The forks buckle. A mechanic named Mo helps drag the Corley to her shop. “You’re lucky,” she says. Sure doesn’t feel like it.":"Мотор кашляет. Вилка подламывается. Механик по имени Мо помогает дотащить «Корли» до мастерской. «Тебе повезло», — говорит. Что-то не похоже.",
  "MO’S GARAGE & SALVAGE YARD UNLOCKED":"ОТКРЫТЫ ГАРАЖ МО И СВАЛКА",
  "The dog trades his professional standards for a mouthful of jerky. The forks are mine to take.":"Пёс меняет профессиональные принципы на кусок мяса. Теперь можно забрать вилку.",
  "Hose connected. Gravity can do the hard work. Now use the empty can on the pump.":"Шланг на месте. За тяжёлую работу отвечает сила тяжести. Теперь примени пустую канистру к колонке.",
  "A can won’t get the gas out by itself. I need to connect a siphon hose first.":"Одна канистра бензин не достанет. Сначала надо подсоединить шланг.",
  "Siphoned a full can of gas at the salvage yard.":"Набрал полную канистру бензина на свалке.",
  "One full can. A little rusty, a little flammable. My kind of vintage.":"Полная канистра. Немного ржавчины, немного огнеопасности. Винтаж по мне.",
  "Empty can → Full fuel can":"Пустая канистра → Канистра с бензином",
  "Installed the salvaged front forks.":"Установил вилку со свалки.",
  "The new forks slide into place. Need a wrench to tighten the axle.":"Новая вилка встала на место. Осталось затянуть ось ключом.",
  "Front forks installed":"Вилка установлена", "Filled the motorcycle’s tank.":"Залил бензин в бак.",
  "Gas in the tank. One less excuse for staying here.":"Бензин в баке. На одну причину торчать здесь меньше.",
  "Tank filled":"Бак заправлен",
  "No point tightening a bent front end. Install the straight forks first.":"Кривую вилку затягивать бессмысленно. Сначала поставь ровную.",
  "The axle’s already tight. I’m keeping the wrench, though.":"Ось уже затянута. А ключ я пока оставлю себе.",
  "Tightened the new front axle.":"Затянул новую переднюю ось.",
  "Axle tightened. That wheel is staying where I put it.":"Ось затянута. Колесо останется там, где я его поставил.",
  "Axle secured":"Ось закреплена",
  "Nothing to fish out right now. I should get my bike running first.":"Пока здесь нечего вытаскивать. Сначала надо починить байк.",
  "Got the photo tin already.":"Жестянку с фотографиями я уже достал.",
  "The magnet catches a photo tin under the grate. Miranda’s contact prints show Ripburger attacking Corley. The Polecats were framed.":"Магнит подцепил жестянку под решёткой. На снимках Миранды Рипбургер нападает на Корли. «Хорьков» подставили.",
  "Those photos and Dad’s tape are enough. Get them onto the screen at Corley’s meeting.":"Этих снимков и папиной записи достаточно. Покажи их на собрании акционеров.",
  "That’s Ripburger… I knew it. Dad gave me this tape. His will. He left Corley Motors to me. Take it. Show them both at the shareholders’ meeting.":"Это Рипбургер… Я знала. Папа дал мне эту кассету. Его завещание. Он оставил компанию мне. Возьми. Покажи и снимки, и запись акционерам.",
  "The cabinet is open. The wrench has done its part.":"Щит открыт. Ключ свою работу сделал.",
  "The bolts give way. Inside: one very dead 20-amp fuse. There are spares on Mo’s workbench.":"Болты поддались. Внутри — совсем мёртвый предохранитель на 20 ампер. Запасные есть у Мо на верстаке.",
  "First I need to open the bolted cabinet.":"Сначала надо открутить болты и открыть щит.",
  "The replacement fuse clicks in. The terminal lights up. Hello, Ripburger.":"Новый предохранитель встал со щелчком. Терминал засветился. Привет, Рипбургер.",
  "No electricity. Fix the power cabinet first.":"Нет электричества. Сначала почини электрощит.",
  "I need to unlock the terminal first. Use it without an inventory item to enter the PIN.":"Сначала надо разблокировать терминал. Сними выбор предмета и нажми «Действие», затем на терминал — появится ввод кода.",
  "Already loaded. The original stays in my pocket.":"Уже загружено. Оригинал останется у меня.",
  "Photos scanned. Ripburger’s little secret is ready for the big screen.":"Снимки отсканированы. Маленький секрет Рипбургера готов к большому экрану.",
  "Tape loaded. Malcolm Corley gets the last word.":"Кассета загружена. Последнее слово за Малкольмом Корли.",
  "“I knew the Polecats didn’t do it. I’ll keep the suits busy. Try the service terminal.”":"«Я знал, что „Хорьки“ ни при чём. Отвлеку этих в костюмах. Попробуй служебный терминал».",
  "The can’s empty. Try the fuel pump at the salvage yard.":"Канистра пустая. Попробуй бензоколонку на свалке.",
  "“Heard the news. I don’t buy it. Your boys are trouble, but not that kind.”":"«Слышал новости. Не верю. Твои ребята любят неприятности, но не такие».",
  "“You’re awake. Good. That suit was asking an awful lot about you.”":"«Очнулся. Хорошо. Тот тип в костюме слишком много о тебе расспрашивал».",
  "Where did the Polecats go?":"Куда уехали «Хорьки»?", "Got anything for siphoning gas?":"Есть чем слить бензин?", "I need something to eat.":"Мне бы чего-нибудь поесть.", "Seen a photographer around here?":"Не видел здесь девушку-фотографа?", "Keep your head down.":"Не высовывайся.",
  "“An engine I can fix. What Ripburger did… we need proof.”":"«Мотор я починю. Но то, что сделал Рипбургер… Нам нужны доказательства».",
  "“Somebody worked hard to make this bike kill you. Let’s disappoint them.”":"«Кто-то очень старался, чтобы этот байк тебя убил. Давай его разочаруем».",
  "What does the bike need?":"Что нужно для ремонта?", "Where do I find the parts?":"Где найти запчасти?", "How do we clear the Polecats?":"Как снять обвинения с «Хорьков»?", "Who taught you to fix bikes?":"Кто научил тебя чинить байки?", "I’ll get to work.":"Пойду займусь делом.",
  "A wrench, a magnet, a fuse. The three food groups of motorcycle repair.":"Ключ, магнит, предохранитель. Три кита мотоциклетного ремонта.",
  "Take the wrench":"Взять гаечный ключ", "Take the pickup magnet":"Взять магнит на тросе", "Take a spare fuse":"Взять предохранитель", "Step away":"Отойти",
  "“I used to ride with Torque. I know a frame-up when I see one. The service terminal feeds their presentation. You didn’t hear that from me.”":"«Я когда-то ездил с Торком. Подставу за версту чую. Служебный терминал подключён к их презентации. Только я тебе ничего не говорил».",
  "Why is the terminal dead?":"Почему терминал не работает?", "Know the access code?":"Знаешь код доступа?", "Owe you one.":"Буду должен.",
  "That conversation has moved on.":"Об этом мы уже поговорили.",
  "“Ripburger paid your boys to escort Corley. Said you’d catch up. They headed east. Your keys? Heard ’em rattle inside that dumpster.”":"«Рипбургер заплатил твоим за сопровождение Корли. Сказал, ты догонишь. Уехали на восток. Ключи? Слышал, как звенят в том контейнере».",
  "“Take the old tap hose. Never could get the beer taste out of it. Maybe gasoline will help.”":"«Бери старый шланг от крана. Пиво из него так и не выветрилось. Может, бензин поможет».",
  "“Last bag of jerky. Tough enough to patch a tire. On the house.”":"«Последняя пачка мяса. Жёсткое — можно шины латать. За счёт заведения».",
  "“Miranda left a photo tin behind the dumpster’s drain grate. Said she’d come back when the suits stopped following her. Something worth hiding.”":"«Миранда спрятала жестянку со снимками за сливной решёткой контейнера. Вернётся, когда типы в костюмах отстанут. Видать, есть что прятать».",
  "“She’s good. Go make some trouble.”":"«Готова. Езжай, устрой им весёлую жизнь».",
  "“Straight front forks. A can of gas. Then use the wrench to tighten the axle. Put the parts on the bike yourself. I’ll check your work.”":"«Ровная передняя вилка. Канистра бензина. Потом затяни ось ключом. Ставь детали на байк сам, а я проверю».",
  "“Salvage yard, down the road. There’s an old fuel pump and a set of forks. Watch the dog. Tools and an empty can are here. The bartender might have a hose.”":"«На свалке вниз по дороге есть вилка и старая колонка. Осторожнее с псом. Инструменты и пустая канистра — здесь. Шланг может быть у бармена».",
  "“My dad. He said you can tell who built an engine by how it sounds. I’d know his work anywhere.”":"«Папа. Он говорил: по звуку двигателя можно понять, кто его собрал. Его работу я узнаю где угодно».",
  "“The photos prove the murder. Dad’s tape proves who inherits the company. Scan the photos, load the tape, and hit transmit.”":"«Снимки докажут убийство. Папина запись — кому достанется компания. Отсканируй фотографии, вставь кассету и включи трансляцию».",
  "“A photographer was following Corley. Ask at the Kickstand. If you find her photos, show them to me.”":"«За Корли следила девушка-фотограф. Спроси в „Кикстэнде“. Найдёшь её снимки — покажи мне».",
  "Borrowed Mo’s wrench. “Bring it back in one piece,” she says. She probably means me.":"Одолжил ключ Мо. «Вернись целым», — говорит. Кажется, она не про ключ.",
  "A pickup magnet on a cable. For when brute force needs a little reach.":"Магнит на тросе. На случай, когда грубой силе не хватает длины рук.",
  "Pocketed a spare 20-amp fuse. Mo calls it planning ahead.":"Положил в карман предохранитель на 20 ампер. Мо называет это предусмотрительностью.",
  "“Fuse blew in the courtyard cabinet. Bolted shut. Whoever fixes it will need a wrench and a 20-amp replacement.”":"«Во дворе, в щите, сгорел предохранитель. Щит на болтах. Понадобится ключ и замена на 20 ампер».",
  "“Corley was sentimental. The service PIN is his first winning race number. It’s on his memorial plaque.”":"«Корли был сентиментальным. Код — его номер в первой победной гонке. Посмотри памятную табличку».",
  "Time to keep moving.":"Пора двигаться дальше.",
  "The terminal needs power first.":"Сначала нужно подать питание на терминал.",
  "ACCESS DENIED. Corley’s first winning race number… it must be written somewhere.":"ДОСТУП ЗАПРЕЩЁН. Номер Корли в первой победной гонке… Где-то же он записан.",
  "ACCESS GRANTED. Photo scanner online. Tape deck ready. The meeting upstairs is about to get interesting.":"ДОСТУП РАЗРЕШЁН. Сканер включён. Дека готова. Собрание наверху скоро станет интереснее.",
  "Your keys are close to where you woke up. Something nearby rattles.":"Ключи рядом с местом, где ты очнулся. Что-то поблизости звенит.",
  "Look at the dumpster. A stuck lid is a good excuse to use your boot.":"Осмотри контейнер. Заклинившая крышка — отличный повод пустить в ход сапог.",
  "Select Kick (4), then click the dumpster on the left.":"Выбери «Пнуть» (4), затем нажми на контейнер слева.",
  "Having keys is different from using them.":"Найти ключи — одно. Воспользоваться ими — другое.",
  "Select the keys in your pockets, then click your motorcycle.":"Выбери ключи в инвентаре, затем нажми на мотоцикл.",
  "Click Bike keys in the inventory, then Ben’s motorcycle on the right.":"Нажми «Ключи от байка» в инвентаре, затем на мотоцикл Бена справа.",
  "The salvage yard has the parts. The dog has objections.":"На свалке есть запчасти. У пса есть возражения.",
  "Ask the bartender for food. Use the jerky on the salvage yard dog, then Use the chrome forks.":"Попроси у бармена еду. Дай мясо псу на свалке, затем забери хромированную вилку действием «Действие».",
  "Talk to the bartender → “I need something to eat.” Select jerky → dog. Select Use → forks. Go to Mo’s, select forks → bike.":"Бармен → «Мне бы чего-нибудь поесть». Мясо → пёс. «Действие» → вилка. Затем в гараж Мо: вилка → байк.",
  "A part in your pocket won’t steer a motorcycle.":"Деталь в кармане мотоциклом не рулит.",
  "Bring the forks back to Mo’s garage and use them on the bike.":"Отнеси вилку в гараж Мо и примени к байку.",
  "Select Front forks from your inventory, then click Ben’s motorcycle at Mo’s garage.":"В гараже Мо выбери «Передняя вилка» в инвентаре и нажми на байк Бена.",
  "The salvage yard fuel pump is dead, but gravity still works.":"Насос на свалке не работает. А сила тяжести — вполне.",
  "Get a hose from the bartender and the empty can at Mo’s. Use the hose, then the can, on the salvage yard pump.":"Возьми шланг у бармена, а пустую канистру — у Мо. На свалке примени к колонке сначала шланг, затем канистру.",
  "Talk to bartender → siphoning gas. Use fuel can at Mo’s to pick it up. At the yard: hose → pump, can → pump. At Mo’s: full fuel can → bike.":"Бармен → вопрос о бензине. У Мо: «Действие» → канистра. На свалке: шланг → колонка, канистра → колонка. У Мо: бензин → байк.",
  "An engine is only as good as the bolts holding it together.":"Даже хороший мотор бесполезен, если всё держится на честном слове.",
  "The new front axle needs tightening. Mo’s workbench has a wrench.":"Переднюю ось нужно затянуть. На верстаке Мо есть ключ.",
  "Use Mo’s workbench → Take the wrench. Select Wrench in your pockets, then click the motorcycle.":"«Действие» → верстак Мо → «Взять гаечный ключ». Выбери ключ в инвентаре и нажми на мотоцикл.",
  "A photographer saw what happened. Try asking at the Kickstand.":"Девушка-фотограф видела, что случилось. Расспроси бармена в «Кикстэнде».",
  "A photo tin is trapped behind the dumpster grate. Mo has something that can reach it.":"Жестянка со снимками застряла за решёткой контейнера. У Мо есть инструмент, которым можно её достать.",
  "Use Mo’s workbench → Take the pickup magnet. Return to the Kickstand, select magnet, and click the dumpster.":"Верстак Мо → «Взять магнит на тросе». Вернись к «Кикстэнду», выбери магнит и нажми на контейнер.",
  "Mo deserves to see what really happened.":"Мо должна увидеть, что случилось на самом деле.",
  "Show the photos to Maureen. Don’t just talk about them.":"Покажи Морин фотографии. Одного разговора недостаточно.",
  "At Mo’s garage, select Evidence photos in your pockets and click Maureen. She will give you Corley’s tape.":"В гараже выбери «Фотографии-улики» и нажми на Морин. Она отдаст кассету Корли.",
  "A dead terminal needs electricity before it needs a password.":"Мёртвому терминалу сначала нужно электричество, а уже потом пароль.",
  "The power cabinet is bolted shut and its fuse is blown. Mo’s workbench has both things you need.":"Щит на болтах, предохранитель перегорел. Всё необходимое есть на верстаке Мо.",
  "Take the wrench and spare fuse from Mo’s workbench. At Corley Motors: use wrench on cabinet, then fuse on cabinet.":"Возьми у Мо ключ и предохранитель. На заводе: ключ → электрощит, затем предохранитель → электрощит.",
  "Corley put his history on the wall. The guard knows why it matters.":"История Корли написана на стене. Охранник знает, почему это важно.",
  "Look at the memorial plaque. His first winning race number is the terminal PIN.":"Осмотри памятную табличку. Номер Корли в первой победной гонке — код терминала.",
  "Select Use and click the service terminal. Enter 2040.":"Выбери «Действие» и нажми на служебный терминал. Введи 2040.",
  "You have two pieces of evidence and one very large audience.":"У тебя два доказательства и очень большая аудитория.",
  "The terminal has a photo scanner and a tape deck. Use both inventory items on it.":"В терминале есть сканер и кассетная дека. Примени к нему оба доказательства.",
  "Select Evidence photos → broadcast terminal. Select Corley’s tape → broadcast terminal.":"Фотографии-улики → терминал трансляции. Кассета Корли → терминал трансляции.",
  "Everything is ready. Let the truth do the talking.":"Всё готово. Пусть теперь говорит правда.",
  "The terminal’s TRANSMIT function is waiting.":"Терминал ждёт команды на трансляцию.",
  "Deselect any inventory item. Choose Use (2), then click the broadcast terminal.":"Сними выбор предмета в инвентаре. Нажми «Действие» (2), затем на терминал трансляции.",
  "You did it. The road is yours.":"Ты справился. Дорога твоя.",
  "Check your journal to look back at the ride.":"Загляни в журнал и вспомни, как всё было.",
  "Start a new ride from the menu whenever you want.":"В любой момент можно начать новую поездку через меню.",
  "Find your keys and reach Mo’s garage":"Найти ключи и добраться до гаража Мо",
  "Salvage and install straight front forks":"Добыть и установить ровную переднюю вилку",
  "Siphon gas and fill the tank":"Слить бензин и заправить байк",
  "Tighten the axle and repair the bike":"Затянуть ось и закончить ремонт",
  "Recover the photographer’s evidence":"Найти фотографии Миранды",
  "Show Mo the photos; get Corley’s will":"Показать Мо снимки и получить завещание Корли",
  "Power up and unlock the service terminal":"Починить и разблокировать терминал",
  "Expose Ripburger at the shareholders’ meeting":"Разоблачить Рипбургера перед акционерами",
};

export function t(value) {
  if (value == null) return '';
  const text=String(value);
  if (Object.hasOwn(messages,text)) return messages[text];
  if(text.endsWith(' added to your pockets')) return `В инвентаре: ${t(text.slice(0,-22))}`;
  const repairs=text.match(/^She needs (.+)\. Use the parts from your pockets on the bike\.$/);
  if(repairs)return `Нужны: ${repairs[1].split(', ').map(t).join(', ')}. Выбирай детали в инвентаре и применяй к байку.`;
  const evidence=text.match(/^Before I transmit, I need to load (.+)\. Select each item, then use it on the terminal\.$/);
  if(evidence)return `Перед трансляцией нужно загрузить: ${evidence[1].split(' and ').map(t).join(' и ')}. Выбери каждый предмет и примени к терминалу.`;
  const wrong=text.match(/^The (.+) won’t help with that\.$/);
  if(wrong){const key=Object.keys(messages).find(key=>key.toLowerCase()===wrong[1]);return `${key?t(key):wrong[1]} — здесь не поможет.`;}
  return text;
}

export function itemCount(count){const mod=count%100,last=count%10;return `${count} ${mod>=11&&mod<=14?'предметов':last===1?'предмет':last>=2&&last<=4?'предмета':'предметов'}`;}
